### ISSUE TITLE
Remove dots

### ISSUE THREAD

**Issue by L1cardo** [Pictarine/CodeMirror-SwiftUI#3]
How to remove these dots?
![image](https://user-images.githubusercontent.com/33802186/93453215-fa72b780-f90b-11ea-8ef9-28bb6d55e4fd.png)

**Comment by marshallino16** [comment]
Hi, 

These dots are displaying "invisible characters" thanks to a CodeMirror plugin. 

It can easily be set as an optional parameter of the view. 

I'll add this in the next version.

**Comment by marshallino16** [comment]
Fix https://github.com/Pictarine/CodeMirror-SwiftUI/commit/ca968732a6c40583f1f1c1775fb0eedb58c64365

You can now use the `showInvisibleCharacters` param.
Check the macOS Demo.
