### ISSUE TITLE
Missing Modes

### ISSUE THREAD

**Issue by L1cardo** [Pictarine/CodeMirror-SwiftUI#4]
I need `toml` badly, but I can not found `toml` mode.
There is the resource but it seems you did not implement it. 
![image](https://user-images.githubusercontent.com/33802186/94103656-b7629800-fe67-11ea-8692-bb8992b52e50.png)

**Comment by marshallino16** [comment]
Hey, 

Thank you for the pull request (https://github.com/Pictarine/CodeMirror-SwiftUI/pull/5) !
